# Generated by Django 5.0.4 on 2024-07-09 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sport')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('birthdate', models.DateField(null=True)),
                ('picture', models.CharField(default='/static/sparky.jpg', max_length=500)),
                ('sex', models.CharField(max_length=1)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.position')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_result', models.CharField(max_length=50)),
                ('assessment_notes', models.CharField(max_length=500)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.assessment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.userprofile')),
            ],
        ),
    ]
