# Generated by Django 5.0 on 2023-12-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('assessment', models.CharField(max_length=150)),
                ('assessment_result', models.CharField(max_length=50)),
                ('assessment_units', models.CharField(max_length=50)),
                ('assessment_notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
