# Generated by Django 5.0 on 2023-12-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_assessment_delete_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assessment',
            new_name='Record',
        ),
    ]
