# Generated by Django 5.0 on 2023-12-19 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_position_sport_alter_record_position_position_sport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.position'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sport'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
