# Generated by Django 5.0 on 2023-12-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_record_position_alter_record_sport_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.position'),
        ),
    ]
