# Generated by Django 5.0 on 2023-12-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_record_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='position',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.position'),
        ),
    ]
